[package]
name = "scranner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rayon = "1.11.0"
reqwest = { version = "0.13", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.18"
trust-dns-resolver = "0.23.2"
